default: hello.c
	gcc hello.c -o hello
	@echo "You can now execute the code by typing './hello'."
	@echo "You may need to do 'chown +x hello' to make sure you have the permisions to run it."
	gcc hello.c -E >> hello.i
	@echo "You can now use any text editor to explore file 'hello.i' or just type 'less hello.i' to read it in the terminal with paging."

