array1: array1.c
	gcc -Wall array1.c -o array1
	@echo "You can now execute the code by typing './array1'"
	@echo "You may need to do 'chown +x array1' to make sure you have the permisions to run it"

array2: array2.c
	gcc -Wall array2.c -o array2
	@echo "You can now execute the code by typing './array2'"
	@echo "You may need to do 'chown +x array2' to make sure you have the permisions to run it"
