main1: main1.c
	gcc -Wall main1.c -o main1
	@echo "You can now execute the code by typing './main1'"
	@echo "You may need to do 'chown +x main1' to make sure you have the permisions to run it"

main2: main2.c
	gcc -Wall main2.c -o main2
	@echo "You can now execute the code by typing './main2'"
	@echo "You may need to do 'chown +x main2' to make sure you have the permisions to run it"

clean:
	rm  -f main1 main2
